### ISSUE TITLE
Update system status on refresh

### ISSUE THREAD

**Issue by JuliusKunze** [KDD-OpenSource/fexum-frontend#110]
Endpoint "calculation-list" returns a list of all currently running calculations each containing 
- id
- current_iteration
- max_iteration
- features (list of ids, None if type != 'fixed_feature_set_hics')
- target (id)
- type (enum ['default_hics', 'fixed_feature_set_hics', ...]). 

A calculation is regarded as running if current_iteration<max_iteration.

**Comment by timediv** [comment]
@nikriek @JuliusKunze where do I get the id from initially before I get notified by a websocket?
Let's say I know the target feature and wanna know what calculations are running involving that target.

I think this endpoint should also return the subset of features, the target and an enum ['default_hics', 'fixed_feature_set_hics']

**Comment by nikriek** [comment]
This is currently not implement. We should also add the `target` id to the output.

**Comment by nikriek** [comment]
Also we do not filter by use for example which we need to do for privacy reasons.

**Comment by nikriek** [comment]
We could add a `created_by` field to the calculation model and use it as a filter

**Comment by timediv** [comment]
done in #113
