### ISSUE TITLE
Save and retrieve current running experiment

### ISSUE THREAD

**Issue by nikriek** [KDD-OpenSource/fexum-frontend#112]
`GET /api/experiments/current` - Retrieve current experiment or 404
`PUT /api/experiments/current/<experiment_id>`- set the current experiment using it's id

**Comment by timediv** [comment]
what's the output?

**Comment by nikriek** [comment]
Same as in all experiment endpoints

**Comment by JuliusKunze** [comment]
This causes update notifications not being pushed.

**Comment by timediv** [comment]
It's not really a bug but breaking changes, I'm on it

**Comment by timediv** [comment]
done in #116
