### ISSUE TITLE
Inaccurate force layout

### ISSUE THREAD

**Issue by danthe96** [KDD-OpenSource/fexum-frontend#121]
Relevance doesn't seem to be weighted enough, a feature with lower relevance should never be closer to the target than one with high relevance. [Here's an example](https://gfycat.com/ArtisticOblongHumpbackwhale).

**Comment by timediv** [comment]
I suspect it has to do with different red. and rel. magnitudes due to the new algorithm

**Comment by timediv** [comment]
@JuliusKunze do these histograms help?

![image](https://user-images.githubusercontent.com/5778449/27258916-59e985ac-5407-11e7-9546-4d9e0f1b7b12.png)
![image](https://user-images.githubusercontent.com/5778449/27258917-6088ce9a-5407-11e7-9615-4790aab2fa49.png)

**Comment by danthe96** [comment]
@JuliusKunze You can use BP6 for testing, API port 8001, websocket port 8000

**Comment by timediv** [comment]
solved in #123
