### ISSUE TITLE
Use samples from backend for feature ranges

### ISSUE THREAD

**Issue by danthe96** [KDD-OpenSource/fexum-frontend#61]
Instead of filtering our samples in the frontend, we should get a new sample from the backend after selecting a feature range. That way, we can avoid "not enough data" when plotting the graph.

**Comment by danthe96** [comment]
@nikriek Update?

**Comment by nikriek** [comment]
One of @xasetl or @marcuspappik?

**Comment by danthe96** [comment]
???

**Comment by xasetl** [comment]
for /samples and /distributions we can now use a max_samples-parameter /distributions(?:/(?P<max_samples>[0-9]+))?.
a dict is returned with the old distribution list and if samples are requested, them as well.
e.g.
```
{
	'distribution': [{'value': 0.0, 'probability': 1.0}, ...],
	'samples': {
		id('Col1'): [0.0, 0.0],
 		id('Col2'): [-0.046074360000000002, -0.047435999999999999],
 		id('Col3'): [0.0, 0.0]
 		.
 		.
 	}
}
```
in case of /samples the default value of max_sample is 10000 and only the samples-dict is returned
{str(feature_id): list(samples)}

**Comment by timediv** [comment]
done in #124
